// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9TY-oahHvsecz7hswl1LIqizD6Ra26ZI',
    appId: '1:305147663280:web:d4747d52aee81015de7c75',
    messagingSenderId: '305147663280',
    projectId: 'catalogo-1eee0',
    authDomain: 'catalogo-1eee0.firebaseapp.com',
    storageBucket: 'catalogo-1eee0.firebasestorage.app',
    measurementId: 'G-489YNL4MPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJGPuXWkTlZPSfO3WJ9i-G3ZFl2csF4NQ',
    appId: '1:305147663280:android:fa42aeed461df4e6de7c75',
    messagingSenderId: '305147663280',
    projectId: 'catalogo-1eee0',
    storageBucket: 'catalogo-1eee0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrRjtZ3y9ubK91VPEcFUrV39VGw6rjo-w',
    appId: '1:305147663280:ios:19bba588bf20e0bfde7c75',
    messagingSenderId: '305147663280',
    projectId: 'catalogo-1eee0',
    storageBucket: 'catalogo-1eee0.firebasestorage.app',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrRjtZ3y9ubK91VPEcFUrV39VGw6rjo-w',
    appId: '1:305147663280:ios:19bba588bf20e0bfde7c75',
    messagingSenderId: '305147663280',
    projectId: 'catalogo-1eee0',
    storageBucket: 'catalogo-1eee0.firebasestorage.app',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9TY-oahHvsecz7hswl1LIqizD6Ra26ZI',
    appId: '1:305147663280:web:5fd7edc05028efa9de7c75',
    messagingSenderId: '305147663280',
    projectId: 'catalogo-1eee0',
    authDomain: 'catalogo-1eee0.firebaseapp.com',
    storageBucket: 'catalogo-1eee0.firebasestorage.app',
    measurementId: 'G-QC039L0CT3',
  );
}
